// License guard for an Apache-2.0 project.
//   --check    fail if any production dependency uses a license outside the allowlist
//   --notices  write THIRD_PARTY_NOTICES.md with the license text of every production dependency
// Only runtime dependencies (package.json "dependencies", walked transitively) end up in the
// Worker and web bundles; dev and build tools are not distributed with Tend 24/7.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ALLOWED = new Set(["MIT", "ISC", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "0BSD", "Unlicense", "CC0-1.0", "BlueOak-1.0.0"]);

interface Pkg {
  name: string;
  version: string;
  license: string;
  repository: string;
  dir: string;
}

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function readJson(path: string): Record<string, any> {
  return JSON.parse(readFileSync(path, "utf8"));
}

/** Node resolution: look in nested node_modules first, then each parent. */
function resolve(name: string, fromDir: string): string | null {
  let dir = fromDir;
  for (;;) {
    const candidate = join(dir, "node_modules", name);
    if (existsSync(join(candidate, "package.json"))) return candidate;
    const parent = dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function licenseOf(meta: Record<string, any>): string {
  if (typeof meta.license === "string") return meta.license;
  if (meta.license?.type) return meta.license.type;
  if (Array.isArray(meta.licenses)) return meta.licenses.map((l: { type: string }) => l.type).join(" OR ");
  return "UNKNOWN";
}

export function productionPackages(): Pkg[] {
  const seen = new Map<string, Pkg>();
  const queue: { name: string; from: string }[] = Object.keys(readJson(join(root, "package.json")).dependencies ?? {}).map(
    (name) => ({ name, from: root }),
  );
  while (queue.length) {
    const { name, from } = queue.shift()!;
    const dir = resolve(name, from);
    if (!dir) continue; // optional dependency not installed on this platform
    const meta = readJson(join(dir, "package.json"));
    const id = `${meta.name}@${meta.version}`;
    if (seen.has(id)) continue;
    const repo = typeof meta.repository === "string" ? meta.repository : meta.repository?.url ?? meta.homepage ?? "";
    seen.set(id, { name: meta.name, version: meta.version, license: licenseOf(meta), repository: String(repo), dir });
    for (const dep of Object.keys({ ...(meta.dependencies ?? {}), ...(meta.optionalDependencies ?? {}) })) {
      queue.push({ name: dep, from: dir });
    }
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}

/** True when an SPDX expression is satisfiable using only allowed licenses. */
export function isAllowed(expr: string): boolean {
  const clean = expr.replace(/[()]/g, " ").trim();
  return clean.split(/\s+OR\s+/).some((alt) => alt.split(/\s+AND\s+/).every((id) => ALLOWED.has(id.trim())));
}

function licenseText(dir: string): string {
  const file = readdirSync(dir).find((f) => /^(license|licence|copying)(\..*)?$/i.test(f));
  return file ? readFileSync(join(dir, file), "utf8").trim() : "(no license file shipped in the package)";
}

const pkgs = productionPackages();
const args = new Set(process.argv.slice(2));

if (args.has("--check") || args.size === 0) {
  const bad = pkgs.filter((p) => !isAllowed(p.license));
  for (const p of pkgs) console.log(`${isAllowed(p.license) ? "ok " : "BAD"}  ${p.license.padEnd(14)} ${p.name}@${p.version}`);
  if (bad.length) {
    console.error(`\n${bad.length} production dependenc${bad.length === 1 ? "y has" : "ies have"} a license not compatible with this project's Apache-2.0 policy.`);
    process.exit(1);
  }
  console.log(`\nAll ${pkgs.length} production dependencies are compatible with Apache-2.0.`);
}

if (args.has("--notices")) {
  const body = [
    "# Third-party notices",
    "",
    "Tend 24/7 is licensed under the Apache License, Version 2.0. The Worker and web bundles include",
    "the following third-party packages. Generated by `npm run licenses:notices`; do not edit by hand.",
    "",
    "| Package | Version | License |",
    "| --- | --- | --- |",
    ...pkgs.map((p) => `| ${p.name} | ${p.version} | ${p.license} |`),
    "",
    ...pkgs.flatMap((p) => [`## ${p.name}@${p.version} (${p.license})`, "", p.repository ? `Source: ${p.repository}` : "", "", "```", licenseText(p.dir), "```", ""]),
  ].join("\n");
  writeFileSync(join(root, "THIRD_PARTY_NOTICES.md"), body);
  console.log(`wrote THIRD_PARTY_NOTICES.md (${pkgs.length} packages)`);
}
